apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  name: deepsparse
  annotations:
    openshift.io/display-name: DeepSparse
spec:
  supportedModelFormats:
    - autoSelect: true
      name: onnx
      version: "1"
  containers:
    - args:
        - --task
        - sentiment-analysis
        - --model_path
        - /mnt/models/model.onnx
      image: quay.io/USER/neural-magic:v1
      name: deepsparse
      imagePullPolicy: Always
  multiModel: false
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000