endpoints:
    - task: yolo
      model: zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned65_quant-none
      route: /spare/yolo
      name: sparse
    - task: yolo
      model: zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none
      route: /dense/yolo
      name: dense
