apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: neural-magic-poc
spec:
  predictor:
    containers:
    - name: kserve-container
      image: quay.io/ltomasbo/neural-magic:yolo
      ports:
      - containerPort: 8080
      resources:
        limits:
          cpu: '2'
          memory: '12Gi'
        requests:
          cpu: '2'
          memory: '12Gi'
