apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    openshift.io/display-name: DeepSparse
  labels:
    opendatahub.io/dashboard: "true"
  name: deepsparse
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8888
    serverType: ovms
  containers:
    - args:
        - --task
        - sentiment-analysis
        - --zoo-model
        - zoo:nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90_quant-none
      image: quay.io/USER/neural-magic:v1
      name: ovms
      imagePullPolicy: Always
  grpcDataEndpoint: port:8001
  grpcEndpoint: port:8085
  multiModel: true
  protocolVersions:
    - grpc-v1
    - v2
  supportedModelFormats:
    - autoSelect: true
      name: onnx
      version: "1"
