---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    #serving.kserve.io/s3-endpoint: minio-api-neural-magic-poc.apps.devcluster.openshift.com # replace with your s3 endpoint e.g minio-service.kubeflow:9000
    #serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-endpoint: minio-service.neural-magic-poc.svc.cluster.local:9000 
    serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-region: "no-region"
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
  name: s3-config
stringData:
  "AWS_ACCESS_KEY_ID": "minio"
  "AWS_SECRET_ACCESS_KEY": "minio_1_2_3"