apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  annotations:
    openshift.io/display-name: nm-vLLM Runtime
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: nm-vllm-runtime
spec:
  containers:
    - args:
        - --port
        - "8000"
        - --model
        - /mnt/models
        - --sparsity
        - sparse_w16a16 
      command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
      image: quay.io/ltomasbo/neural-magic:nm-vllm
      name: kserve-container
      ports:
        - containerPort: 8000
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: onnx
